name: Linux Build with Maven 

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
  JKUBE_REPOSITORY: https://github.com/eclipse/jkube.git
  JKUBE_REVISION: master

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Linux Build With Maven 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.3.3
          native-image: true
      - name: Clone JKube
        run: |
          rm -rf jkube \
          && git clone "$JKUBE_REPOSITORY" --branch "$JKUBE_REVISION" jkube
      - name: Install JKube
        run: mvn ${MAVEN_ARGS} -f "jkube/pom.xml" clean install -DskipTests -Djacoco.skip=true
      - name: Run Integration tests
        run: |
          gradle clean build
          gradle nativeCompile
          gradle k8sBuild
          docker run --rm demos/jkube-spring-boot3-native-image-demo:latest 
